version: "3.8"
services:
  swa_1:
    build:
      context: .
      args: 
        - APP_NAME=swa_1 
  swa_2:
    build:
      context: .
      args: 
        - APP_NAME=swa_2          
  envoy:
    image: envoyproxy/envoy:v1.21.0
    depends_on:
      - swa_1
      - swa_2
    ports:
        - "8080:8080"
        - "9901:9901"
    volumes:
        - "./envoy.yaml:/etc/envoy/envoy.yaml"

